const savedTheme = localStorage.getItem("golden-theme");
const systemTheme = window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark";
document.documentElement.dataset.theme = savedTheme || systemTheme;

const page = document.body.dataset.page || "home";
const navItems = [["Home", "index.html", "home"], ["About", "about.html", "about"], ["Work", "projects.html", "work"], ["Services", "services.html", "services"], ["Collaboration", "collaboration.html", "collaboration"], ["Contact", "contact.html", "contact"]];
const navMarkup = `<header class="site-header" id="siteHeader"><nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="index.html" class="flex items-center gap-3"><span class="logo-mark" aria-hidden="true">GS</span><span class="hidden sm:block"><strong class="block text-sm">Golden Sunday</strong><small class="text-xs text-[var(--muted)]">Frontend Engineer</small></span></a><div class="hidden items-center gap-6 lg:flex">${navItems.map(([label, href, key]) => `<a class="nav-link text-sm text-[var(--muted)] transition hover:text-[var(--ink)]" ${page === key ? 'aria-current="page"' : ""} href="${href}">${label}</a>`).join("")}</div><div class="flex items-center gap-2"><button class="theme-toggle grid h-10 w-10 place-items-center rounded-xl border border-[var(--line)] text-[var(--ink)]" type="button" aria-label="Switch theme"><span class="theme-icon"></span></button><a class="hidden rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-bold text-[var(--accent-ink)] transition hover:brightness-95 sm:inline-flex" href="contact.html">Let's Work Together</a><button id="menuToggle" class="grid h-10 w-10 place-items-center rounded-xl border border-[var(--line)] lg:hidden" type="button" aria-expanded="false" aria-controls="mobilePanel" aria-label="Open navigation">☰</button></div></nav><div class="mobile-panel px-5 pb-5 lg:hidden" id="mobilePanel"><div class="flex flex-col gap-1">${navItems.map(([label, href, key]) => `<a class="rounded-xl px-3 py-3 text-sm text-[var(--muted)] hover:bg-[var(--surface-2)]" ${page === key ? 'aria-current="page"' : ""} href="${href}">${label}</a>`).join("")}<a class="mt-2 rounded-xl bg-[var(--accent)] px-3 py-3 text-center text-sm font-bold text-[var(--accent-ink)]" href="contact.html">Let's Work Together</a></div></div></header>`;
document.body.insertAdjacentHTML("afterbegin", navMarkup);

function updateThemeButtons() { const light = document.documentElement.dataset.theme === "light"; document.querySelectorAll(".theme-icon").forEach((el) => { el.textContent = light ? "☼" : "☾"; el.parentElement.setAttribute("aria-label", light ? "Switch to dark mode" : "Switch to light mode"); }); }
document.querySelectorAll(".theme-toggle").forEach((button) => button.addEventListener("click", () => { const next = document.documentElement.dataset.theme === "light" ? "dark" : "light"; document.documentElement.dataset.theme = next; localStorage.setItem("golden-theme", next); updateThemeButtons(); }));
updateThemeButtons();
const menuToggle = document.getElementById("menuToggle");
const mobilePanel = document.getElementById("mobilePanel");
menuToggle?.addEventListener("click", () => { const open = mobilePanel.classList.toggle("open"); menuToggle.setAttribute("aria-expanded", String(open)); menuToggle.setAttribute("aria-label", open ? "Close navigation" : "Open navigation"); menuToggle.textContent = open ? "×" : "☰"; });
window.addEventListener("scroll", () => document.getElementById("siteHeader")?.classList.toggle("scrolled", window.scrollY > 12), { passive: true });
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("visible"); observer.unobserve(entry.target); } }), { threshold: .08 });
document.querySelectorAll(".reveal").forEach((element) => observer.observe(element));
document.querySelectorAll("[data-year]").forEach((el) => el.textContent = new Date().getFullYear());
